# Generated by Django 5.0 on 2023-12-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_client_mailings_message_delete_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
