# Generated by Django 4.2.7 on 2023-12-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_client_user_alter_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='время рассылки'),
        ),
    ]
