# Generated by Django 4.2.7 on 2023-12-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_mailings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='periodicity',
            field=models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='once_a_day', verbose_name='Переодичность'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='state',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='start', max_length=10, verbose_name='Статус'),
        ),
    ]
