# Generated by Django 4.2.7 on 2023-12-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_mailings_periodicity_alter_mailings_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='время рассылки'),
        ),
    ]
