# Generated by Django 4.2.7 on 2023-12-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_mailings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
